spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver


#mybatis
mybatis:
  type-aliases-package: com.lanou.bean
  mapper-locations: classpath:mappers/*.xml

#mapper
#mappers 多个接口时逗号隔开
mapper:
  mappers: com.lanou.util.MyMapper
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


server:
  port: 8766

